---
- name: Install Kibana
  hosts: kibana
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Add Elastic GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elastic repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present

    - name: Install Kibana
      apt:
        name: kibana
        state: present
        update_cache: yes

    - name: Configure Kibana
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#?server.port', line: 'server.port: 5601' }
        - { regexp: '^#?server.host', line: 'server.host: "0.0.0.0"' }
        - { regexp: '^#?elasticsearch.hosts', line: 'elasticsearch.hosts: ["http://192.168.56.11:9200"]' }

    - name: Enable and start Kibana
      systemd:
        name: kibana
        enabled: yes
        state: started
