---
- name: Install Logstash
  hosts: logstash
  become: yes

  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Add Elastic GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elastic repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present

    - name: Install Logstash
      apt:
        name: logstash
        state: present
        update_cache: yes

    - name: Configure Logstash pipeline
      copy:
        dest: /etc/logstash/conf.d/main.conf
        content: |
          input {
            beats {
              port => 5044
            }
          }
          output {
            elasticsearch {
              hosts => ["192.168.56.11:9200"]
              index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
            }
          }

    - name: Enable and start Logstash
      systemd:
        name: logstash
        enabled: yes
        state: started
