---
- name: Deploy Elasticsearch
  hosts: elasticsearch
  become: yes
  roles:
    - elasticsearch

- name: Deploy Logstash
  hosts: logstash
  become: yes
  roles:
    - logstash

- name: Deploy Kibana
  hosts: kibana
  become: yes
  roles:
    - kibana
